### PR TITLE
Add Actions master

### PR DESCRIPTION
**Pull request by DanGM96**
This is the first of three identical PRs, I'm not sure if there is a way to make it all in just one PR.

It implements GitHub Actions to automate every build as a way to make early versions more accessible for whoever may want to test new things without having to build on their own.

The action is triggered on every push, pull request and every 3 months (because the artifacts are automatically deleted by GitHub after 90 days).

If there is anything you'd like I change or even remove the PR just give me a call. 😁

### CODE REVIEW

**Comment by ccomrade** [comment]
Looks good. Is it possible to request one specific version of MSVC? Static linking of MSVC runtime can be safely switched off with VS2005 compiler. It's because Crysis DLLs depend on VC++ 2005 DLLs anyway. This makes the resulting executables much smaller. To do this, set `CMAKE_MSVC_RUNTIME_LIBRARY` to `MultiThreadedDLL`. I also prefer using NMake over VS solution files, but both work just fine with CMake.

**Comment by DanGM96** [comment]
Just updated the actions to use `MultiThreadedDLL` and NMake. The built files are now about the same size as yours. Tried a little with no crashes and everything seems to be working fine.
What do you think?

**Comment by ccomrade** [comment]
Can you open the resulting EXEs in [Dependency Walker](https://www.dependencywalker.com/) and check their dependencies? It should look like this:

image

**Comment by DanGM96** [comment]
Got this but I have no idea what to change to make it like yours. Tried installing vcredist2005 and changing the toolset to 8.0 but it's always the same dependencies. 😕 
image

**Comment by ccomrade** [comment]
It's because some modern MSVC compiler was used. The point is that Windows doesn't provide many of these DLLs by default. You have to install vcredists to get them. This is why the default c1-launcher build settings produce big EXEs to make sure they don't depend on any optional DLLs. However, as i said above, you can safely make them smaller if you use compiler from VS2005. Crytek used this compiler to build Crysis. That means Crysis requires vcredist2005 to be installed, so the launcher EXEs can safely depend on it.

**Comment by ccomrade** [comment]
By the way, it seems `toolset` doesn't support anything below 14:
https://github.com/ilammy/msvc-dev-cmd/blob/f456b805b3f63911738cb71d4f255e4e129c7e7a/index.js#L107
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line#vcvarsall-syntax
(scroll down to `vcversion`)

**Comment by anzz1** [comment]
Yes @ccomrade is wise to use same MSVC version 2005 as the game, to not add additional dependencies which game did not originally have. Most people these days don't even know what "Dependency Walker" is or what does things like C/C++ runtimes and dynamic link library imports mean.

Modern MSVC is unfortunately trying to push [the new UCRT](https://learn.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt?view=msvc-170) hard which is bullshit. It is very hard to avoid, and static linking makes executables super large. It is much harder now to make small apps without dependencies, and you have to resort to strange tricks to force MSVC to link against msvcrt.dll which exist on all Windows systems by default. Lot of stuff can break and generally not worth the effort. Other way is to completely cut out CRT altogether, but that also need tricks on modern MSVC because it'll try pushing in the UCRT anyway at every step of the way. And you need to recreate all CRT functions from the very basics, like memset, strcpy, etc. Very annoying.

So best and also the easiest way to do everything correctly, is do exactly like @ccomrade did and use MSVC 2005 instead of a more modern one. No bag of tricks required, no UCRT dependency. But while GitHub actions are great, they do not unfortunately provide MSVC 2005 runner. So with GitHub action, it's never possible to do this correctly, and need to keep making them by hand.

**Comment by DanGM96** [comment]
Oh, I had forgotten about this. Thank you for the insight @anzz1 

I never knew much about MSVC and all I wanted was to help automatize this step. I have tried so many things on my fork to make it work, but I was never successful.
We could still try and do it all from scratch on GH Actions. If I knew every little detail of the build process, including all software installation links. And run it through PowerShell.

And if that still not possible we can just close this PR.

**Comment by ccomrade** [comment]
Hello, i have finally managed to make VS2005 compiler available in GitHub Actions. Using a custom Docker image running the compiler via Wine on Linux. It's actually the same setup that i use locally. Before it, i used Windows Vista inside a VM. Linux + Wine is a surprisingly better option than Windows Vista SDK on modern Windows. Also, there's no container support for Windows in GitHub Actions.

So, we can close this PR. Thanks a lot for it though. I took inspiration from it and used [ilammy/msvc-dev-cmd](https://github.com/ilammy/msvc-dev-cmd) to easily setup the environment in VS2022 build jobs.

**Comment by anzz1** [comment]
That is a good solution, and it is wise to use the same compiler which also built the game binaries and libraries, in this case VS2005, to compile any additional stuff.

However a tip for the future, if the only thing you actually need is to link against `msvcrt.lib` (for maximum compatibility and lose requirement of having any redistributable packages installed), it is much easier to simply provide it in the project and force MSVC to link against it with project options, then add a CRT stub so the modern MSVC doesn't complain about it missing and also add a few compiler options to disable stack canaries and other such nonsense.

Example of such thing I've done in my project:
[CRT stub](https://github.com/anzz1/micro-web-server/blob/master/win32/inc/w32_crt_stub.h)
[Project options](https://github.com/anzz1/micro-web-server/blob/master/win32/premake5.lua) (premake5)
[Github CI Action](https://github.com/anzz1/micro-web-server/blob/master/.github/workflows/ci.yml) (pretty much a default setup)

I chose to include the msvcrt.lib as a file in the project, but is also possible to create it programmatically if wanted to using the `dumpbin` and `lib` tools present in MSVC toolkit.
Here is such CI action which shows the simple process: https://github.com/namazso/msvcrt.lib/blob/master/.github/workflows/ci.yml

Ultimately it is pretty easy to link against the original msvcrt aka "NT CRT" when all the hurdles are understood and cleared, but it is still unnecessarily complicated which is stupid, but that's the shit we need to deal with nowadays with these "modern" toolchains. This should be a simply switch in project options of Visual Studio, to not have to use tricks to make the compiler do what you want.

**Comment by ccomrade** [comment]
Ah nice stuff. Thanks for the links. You avoid even crt0 completely. Interesting. It would be nice to stop using the runtime library to allow the launcher to show some nice error message when VS2005 runtime library required by the engine is missing. Together with a link where to download it. The same with DirectX libraries, which is possible even now because the launcher doesn't link against any DirectX DLL.

Currently, the runtime library should be needed only for `std::string` and exceptions. They are used for fatal errors to make the code clean without error handling ifs all over the place. However, a global function that shows/prints an error message and then calls `exit(1)` would also work. It's ok if some handles stay open because OS will clean them up anyway. No exceptions would also reduce size of the exes a bit. And `std::string` can be replaced with a custom implementation of course.

Let's see. I'm a bit worried about potential maintenance increase. As you said, it's tricky. I certainly don't want to fix some mysterious issues with the latest toolchain each time Microsoft updates it. Crysis has plenty issues of its own. :sweat_smile: Right now, the project doesn't need anything special from the toolchain and just works with basically any MSVC version. Although only MSVC from VS2005 actually matters. The other ones are just nice to have.

The latest MSVC is supported for these reasons:
1. To use its improved static code analysis and warnings to catch potential problems in the code. Well, MSVC is not the right choice for this, but at least something.
2. To make life easier for other people.

If someone wants to mess with the code, all they need to do is to open the project in some Visual Studio with C++ stuff installed and they are ready to go. Either ask CMake to generate those strange solution files or open the project directly in modern VS. That's it. Or at least i hope so because i don't use VS myself. :sweat_smile: And they can even use the standard library as usual. No restrictions. Except that if they want to contribute, then VS2005 will obviously reject all modern C++ features. One bright exception being `override`, which was a non-standard extension back then.

**Pull request closed without merging**
